name: docker_push

on:
  workflow_dispatch:

env:
  BOGUS: bogus

jobs:
  gobuild:
    runs-on: ubuntu-latest

  steps:
    - run: echo ${{ env.BOGUS }}
  
    - name: repo checkout
      uses: actions/checkout@v3

