name: docker_push

on:
    workflow_dispatch:

env:
    XX: YY

jobs:
    gobuild:
        runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
            with:
                go-version: '^1.21.4'

        - run: go version