name: docker_push

on:
  workflow_dispatch:

env:
  BOGUS: bogus


jobs:
  docker:
    # always build and package
    runs-on: ubuntu-latest
  
    steps:
      - run: echo ${{ env.BOGUS }}
    
      - name: repo checkout
        uses: actions/checkout@v3
  
  